---

# https://github.com/sbaudoin/yamllint/issues/16
# Support for common YAML templates (specifically Helm)
ignore: |
  manifests/charts/aeraki/templates/deployment.yaml
  manifests/charts/aeraki/templates/service.yaml
  manifests/charts/aeraki/templates/serviceaccount.yaml

extends: default

rules:
  braces:
    level: warning
    max-spaces-inside: 1
  brackets:
    level: warning
    max-spaces-inside: 1
  colons:
    level: warning
  commas:
    level: warning
  comments: disable
  comments-indentation: disable
  document-start: disable
  empty-lines:
    level: warning
  hyphens:
    level: warning
  indentation:
    level: warning
    indent-sequences: consistent
  line-length:
    level: warning
    allow-non-breakable-inline-mappings: true
  truthy: disable
